# Copyright 2018-2025 the Deno authors. MIT license.

[package]
name = "deno_canvas"
version = "0.74.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "OffscreenCanvas implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
bytemuck.workspace = true
deno_core.workspace = true
deno_error.workspace = true
thiserror.workspace = true
deno_image.workspace = true
deno_webgpu.workspace = true
